import invariant from "tiny-invariant";
import { Movement } from "@prisma/client";
import type { Decimal } from "@prisma/client/runtime";
import { Field, Form, Formik } from "formik";
import type { FieldProps, FormikHelpers } from "formik";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import type { FunctionComponent } from "react";
import { z } from "zod";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import Link from "next/link";

type FormValues = { type: string; amount: number; description: string };

const initialData: FormValues = {
  description: "",
  amount: 0,
  type: "",
};

const CurrentBalance: FunctionComponent<{
  amount: Decimal | null | undefined;
  loading: boolean;
}> = ({ loading, amount }) => {
  return amount ? (
    <h1 className="text-2xl">
      {loading ? (
        <span>Recalculating...</span>
      ) : (
        <>
          <span className="hidden sm:inline">Current balance</span>
          <span className="inline sm:hidden">Balance</span>
          <span> ${(amount as unknown as string) || 0}</span>
        </>
      )}
    </h1>
  ) : null;
};

const Movements: FunctionComponent<{
  data: Movement[] | undefined;
  loading: boolean;
}> = ({ data, loading }) => {
  const router = useRouter();

  const getPageURL = (type: "inc" | "dec") => {
    try {
      const pageQuery = router.query.page || "1";
      invariant(typeof pageQuery === "string", "Page should be a string");

      const page = Number(pageQuery);
      invariant(!isNaN(page), "Page should be a number");

      const pageCalculated =
        type === "dec" ? Math.abs(page - 1 === 0 ? page : page - 1) : page + 1;

      return `/?page=${pageCalculated}`;
    } catch (error) {
      console.info(error);
      return "";
    }
  };

  return (
    <section className="flex gap-4">
      <Link href={getPageURL("dec")}>{"<"}</Link>
      <table>
        <thead>
          <tr className="flex gap-2">
            <th>Amount</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {loading ? (
            <span>Wait...</span>
          ) : (
            data?.map((movement) => (
              <tr key={movement.id} className="flex gap-2">
                <td>${movement.amount as unknown as string}</td>
                <td>{movement.description}</td>
              </tr>
            ))
          )}
        </tbody>
      </table>
      <Link href={getPageURL("inc")}>{">"}</Link>
    </section>
  );
};

const validation = z
  .object({
    amount: z.number().positive().safe(),
    description: z.string(),
    type: z.string().min(1, "Select an option first"),
  })
  .required();

export default function Home() {
  const router = useRouter();
  const {
    data: amountData,
    isRefetching: amountLoading,
    refetch: refetchAmount,
  } = api.movement.getBalance.useQuery();

  const {
    data: movementData,
    isRefetching: movementLoading,
    refetch: refetchMovement,
  } = api.movement.get.useQuery(Number(router.query.page as unknown as string));

  const { isLoading, mutateAsync } = api.movement.create.useMutation();
  const { data: sessionData } = useSession();

  const handleSubmit = async (
    formValues: FormValues,
    helpers: FormikHelpers<FormValues>
  ) => {
    try {
      let amount = Number(formValues.amount);
      amount = formValues.type === "decrease" ? amount * -1 : amount;
      await mutateAsync({ amount, description: formValues.description });

      void refetchAmount();
      void refetchMovement();

      helpers.resetForm();
    } catch (error) {
      console.error("error while sending expense", error);
    }
  };

  const handleValidation = (formValues: FormValues) => {
    const errors: Record<keyof FormValues, string | undefined> = {
      amount: undefined,
      description: undefined,
      type: undefined,
    };

    const response = validation.safeParse(formValues);
    if (response.success) {
      return {};
    } else {
      const newErrors = response.error.issues.reduce(
        (obj, err) => ({
          ...obj,
          [err.path[0] as string]: err.message,
        }),
        errors
      );
      return newErrors;
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative mx-auto min-h-full bg-gradient-to-b from-[#2e026d] to-[#15162c] px-6 text-white">
        <div className="container mx-auto flex flex-col">
          <div className="flex items-center justify-between">
            <CurrentBalance
              loading={isLoading || amountLoading}
              amount={amountData?._sum.amount}
            />

            <header className="flex justify-end">
              <button
                className="rounded-full bg-white/10 px-4 py-2 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={
                  sessionData ? () => void signOut() : () => void signIn()
                }
              >
                {sessionData ? "Sign out" : "Sign in"}
              </button>
            </header>
          </div>

          <Movements loading={movementLoading} data={movementData} />

          <hr />

          <Formik
            validate={handleValidation}
            initialValues={initialData}
            onSubmit={(values, props) => handleSubmit(values, props)}
          >
            {({ errors, isSubmitting, isValidating, values }) => (
              <div className="mt-4">
                <Form className="flex flex-col gap-4">
                  <Field name="amount" placeholder="420" required>
                    {({ field, meta }: FieldProps) => (
                      <label>
                        <span>Amount</span>
                        <div className="relative">
                          <span className="absolute left-0 pl-1 text-black">
                            $
                          </span>
                        </div>
                        <input
                          className="pl-4 pr-2 text-black"
                          required
                          type="number"
                          {...field}
                        />
                        {meta.touched && meta.error && (
                          <div className="text-red-500">{meta.error}</div>
                        )}
                      </label>
                    )}
                  </Field>

                  <Field name="description">
                    {({ field, meta }: FieldProps) => (
                      <label className="flex flex-col items-start">
                        <span>Description</span>
                        <input
                          className="px-2 py-2 text-black"
                          required
                          placeholder="Whiskas"
                          type="string"
                          {...field}
                        />
                        {meta.touched && meta.error && (
                          <div className="text-red-500">{meta.error}</div>
                        )}
                      </label>
                    )}
                  </Field>

                  <div className="flex flex-col">
                    <div className="flex gap-4">
                      <label
                        className={`select-none bg-slate-500 px-2 py-2 ${
                          values.type === "increase" ? "bg-slate-600" : ""
                        }`}
                      >
                        <Field
                          className="hidden"
                          type="radio"
                          name="type"
                          value="increase"
                        />
                        <span>Add +</span>
                      </label>
                      <label
                        className={`select-none bg-slate-500 px-2 py-2 ${
                          values.type === "decrease" ? "bg-slate-600" : ""
                        }`}
                      >
                        <Field
                          className="hidden"
                          type="radio"
                          name="type"
                          value="decrease"
                        />
                        <span>Remove -</span>
                      </label>
                    </div>
                    {errors.type && (
                      <span className="text-red-500">{errors.type}</span>
                    )}
                  </div>

                  <div>
                    <button
                      disabled={isSubmitting || isLoading || isValidating}
                      type="submit"
                      className="rounded bg-gray-500 px-2 py-2"
                    >
                      Send expense
                    </button>
                  </div>
                </Form>
              </div>
            )}
          </Formik>
        </div>
      </main>
    </>
  );
}
